---
- name: Ensure unzip is installed
  apt:
    name: unzip
    state: present
  become: true

- name: Download Android Studio
  get_url:
    url: "{{ android_studio_download_url }}"
    dest: "{{ download_dir }}/android-studio-{{ android_studio_version }}.tar.gz"
    force: false
    checksum: "sha256:{{checksum_sha256}}"

- name: Download only? (debug)
  meta: end_play
  when: download_only

- name: Extract Android Studio
  ansible.builtin.unarchive:
    src: "{{ download_dir }}/android-studio-{{ android_studio_version }}.tar.gz"
    dest: "{{ android_studio_install_dir | dirname }}"
    remote_src: yes
    creates: "{{ android_studio_install_dir }}/bin/studio.sh"

- name: Create a symbolic link to start Android Studio
  ansible.builtin.file:
    src: "{{ android_studio_install_dir }}/bin/studio.sh"
    dest: "/usr/local/bin/android-studio"
    state: link
  become: true

- name: Set permissions for Android Studio
  ansible.builtin.file:
    path: "{{ android_studio_install_dir }}"
    mode: "0755"
    recurse: yes
    state: directory

- name: Add Android Studio to the system path
  lineinfile:
    dest: "~/.bashrc"
    line: 'export PATH="$PATH:{{ android_studio_install_dir }}/bin"'
    state: present
  become: true
  become_user: "{{ ansible_env.USER }}"
