---
- name: pre
  include_tasks: pre.yml

# from: https://chat.openai.com/c/e6d3e415-b6c0-4aba-8bd8-09e7cbb101b2
# and https://developer.android.com/studio/index.html

- name: from ChatGPT
  include_tasks: from AI.yml